server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  
spring:
  datasource:
      hikari:
          jdbc-url : jdbc:mariadb://localhost:3306/book
          username : "root"
          password : "root"
          pool-name: dataSource
          driverClassName : org.mariadb.jdbc.Driver

  jpa:
    open-in-view: true #뭔지 한번 찾아봐야한다.
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #내가 적은 이름 그대로 컬럼명이 만들어짐
    show-sql: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400  # 초
 
  